export const AcademicInformation = {
  entranceAcademicYear: "2017",
  campus: "main",
  program: "MD-Medicine",
  entranceTerm: "SP-Spring Semester",
};

export const documentsUser = [
  {
    title: "PHSU ID photo",
    important: true,
    upload: true,
    trash: true,
    visibility: false,
  },
  {
    title: "Photo 2x2 -",
    important: false,
    upload: true,
    trash: false,
    visibility: false,
  },
  {
    title: "Health Insurance card (Yearly)",
    important: false,
    upload: true,
    trash: false,
    visibility: false,
  },
  {
    title: "Car Licence",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "NPI number =",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Law 300 Certificate - History of Sex Offenses",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title:
      "CPR certificate - AHA FOR HEALTHCARE PROVIDERS (Expiration: 2 years)",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "HIPAA certificate (Expiration: 2 years)",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "OSHA certificate (Expiration: 2 years)",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Background Check (Certiphi)",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "PR Health Certificate (VDRL + PPD)",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "TB Screening + Chest X-Ray",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title:
      "Updated Immunization Record \n Vaccination Exemption Form + Support Documentation",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Vaccination Exemption Form + Support Documentation",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Flu Vaccine",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Varicella (two doses) + titers",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Hepatitis (3 doses) + titers",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "COVID Vaccine - 3 doses",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Drug screening - 10 panel",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Mask fit Alpha Protech N 95 (Yearly)",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Supporting Document for Drug Test",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
  {
    title: "Physician Report",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
  },
];
