export const documentsUser = [
  {
    title: "PHSU ID photo",
    important: true,
    upload: true,
    trash: true,
    visibility: false,
    textRed: "",
  },
  {
    title: "Photo 2x2",
    important: true,
    upload: true,
    trash: false,
    visibility: false,
    textRed: "",
  },
  {
    title: "Health Insurance card",
    important: true,
    upload: true,
    trash: false,
    visibility: false,
    textRed: "(Yearly)",
  },
  {
    title: "Car Licence",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "NPI number",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "Law 300 Certificate - History of Sex Offenses",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title:
      "CPR certificate - AHA FOR HEALTHCARE PROVIDERS (Expiration: 2 years)",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "HIPAA certificate",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "(Expiration: 2 years)",
  },
  {
    title: "OSHA certificate",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "(Expiration: 2 years)",
  },
  {
    title: "Background Check (Certiphi)",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "PR Health Certificate (VDRL + PPD)",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "TB Screening + Chest X-Ray",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title:
      "Updated Immunization Record Vaccination Exemption Form + Support Documentation, Flu Vaccine Varicella (two doses) + titers, Hepatitis (3 doses) + titers",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "COVID Vaccine - 3 doses",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "Drug screening - 10 panel",
    important: false,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "Mask fit Alpha Protech N 95",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "(Yearly)",
  },
  {
    title: "Supporting Document for Drug Test",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
  {
    title: "Physician Report",
    important: true,
    upload: false,
    trash: false,
    visibility: true,
    textRed: "",
  },
];
