export const initialValues = {
  email: "",
  cell_phone: "",
  studentid: "",
  firstname: "",
  middlename: "",
  lastname: "",
  secondlastname: "",
  birthdate: "",
  line1: "",
  line2: "",
  state: "",
  city: "",
  zipcode: "",
  alternative_phone: "",
  institucional_email: "",
  entranceYear: "",
  campusMain: "",
  entranceTerm: "",
  program: "",
}