export const initialValues = {
  first_name: "",
  middle_name: "",
  last_name: "",
  second_last_name: "",
  student_id: "",
  birthdate: "",
  cell_phone: "",
  alternative_phone: "",
  email: "",
  institucional_email: "",
  entrance_year: "",
  campus: "",
  entrance_terms: "",
  address_line1: "",
  address_line2: "",
  address_city: "",
  address_state: "",
  address_zipcode: "",
  program: "",
}