export const UserProfile = {
  email: "example@example.com",
  cell_phone: "1234567890",
  student_id: "123456789",
  first_name: "John",
  middle_name: "Doe",
  last_name: "Smith",
  second_last_name: "Johnson",
  birthdate: "1990-01-01",
  address_line1: "123 Main Street",
  address_line2: "Apt 4B",
  address_state: "California",
  address_city: "Los Angeles",
  address_zipcode: "12345",
  password: "password",
  alternative_phone: "74487-839483-9494",
  institucional_email: "example@example.com",
  entrance_year: "2017",
  campus: "main",
  entrance_terms: "uwusito",
};
